nome = str(input("Digite seu nome completo:"))
print("Analizando seu nome...")
print(f"Seu nome em maiúsculas é {nome.upper()}")
print(f"Seu nome em minúsculas é {nome.lower()}")
print(f"Seu nome tem ao todo {len(nome.replace(" ", ""))}")
print(f"Seu primeiro nome é {nome.split()[0]}")